resources:
  - name: cron_trigger
    type: CronTrigger
    configuration:
      interval: '0 1 * * *'     # Once a day

pipelines:
  - name: pipeline_scheduled_triggers
    configuration:
      retentionPolicy:
        maxAgeDays: 30
        minRuns: 10
    steps:
      - name: step_1
        type: Bash
        configuration:
          inputResources:
            - name: cron_trigger
        execution:
          onExecute:
            - printenv
